@Managemt.Api_HostAddress = http://localhost:5175

POST {{Managemt.Api_HostAddress}}/financing/
Content-Type: application/json

{
    "ContractNumber": "ACF"
}
###

GET {{Managemt.Api_HostAddress}}/token
Content-Type: application/json

###
POST {{Managemt.Api_HostAddress}}/pagamentos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkJhdG1hbiIsInJvbGUiOiJNYW5hZ2VyIiwibmJmIjoxNzE5MDk0NDY5LCJleHAiOjE3MTkxMDE2NjksImlhdCI6MTcxOTA5NDQ2OX0.59qwbazkkHBn-WLxAFGEJQ06idtUQC6ksGf6Jgvhp7s

{
    "NumeroContrato": "ACF",
    "Preco": 1.99,
    "Quantidade": 1
}
###
