@Managemt.Api_HostAddress = http://localhost:5175

POST {{Managemt.Api_HostAddress}}/financing/
Content-Type: application/json

{
    "ContractNumber": "ACF"
}
###

GET {{Managemt.Api_HostAddress}}/pagamentos
Content-Type: application/json
###

GET {{Managemt.Api_HostAddress}}/token
Content-Type: application/json

###
POST {{Managemt.Api_HostAddress}}/pagamentos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkJhdG1hbiIsInJvbGUiOiJNYW5hZ2VyIiwibmJmIjoxNzE5MjM1Nzg5LCJleHAiOjE3MTkyNDI5ODksImlhdCI6MTcxOTIzNTc4OX0.uyS9CEA9IbLsbfklfG1gaFYe2XoWcLpLjn-5vYajGHs

{
    "NumeroContrato": "",
    "Preco": 1.99,
    "Quantidade": 1
}
###
