@Managemt.Api_HostAddress = http://localhost:5175

POST {{Managemt.Api_HostAddress}}/financing/
Content-Type: application/json

{
    "ContractNumber": "ACF"
}
###

POST {{Managemt.Api_HostAddress}}/pagamentos
Content-Type: application/json

{
    "NumeroContrato": "ACF",
    "Preco": 1.99,
    "Quantidade": 1
}
###
